version: '3.7'

services:
  sqlite-db:
    image: nouchka/sqlite3
    container_name: sqlite-db
    volumes:
      - ./DB.db:/DB.db  
    networks:
      - superset-net

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_ENV=development
      - FLASK_APP=superset
      - SUPERSET_SECRET_KEY=mysecretkey  
    ports:
      - "9090:8088"
    depends_on:
      - sqlite-db
    volumes:
      - superset_home:/app/superset_home  
    networks:
      - superset-net
    entrypoint:
      - /bin/sh
      - -c
      - |
        superset db upgrade && 
        superset load_examples &&
        superset init &&
        superset run -p 8088 --with-threads --reload
    restart: always

networks:
  superset-net:
    driver: bridge

volumes:
  superset_home:
